version: "3"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel_docker
    ports:
      - 8080:8080
    volumes:
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./public:/var/www/public
      - ./routes:/var/www/routes
      - ./tests:/var/www/tests
    links:
      - mysql
      - redis
    command: "/bin/sh -c 'php artisan migrate && php artisan serve --host=0.0.0.0 --port=8080'"
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel_docker
      DB_USERNAME: app
      DB_PASSWORD: password
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
      APP_ENV: development
      APP_DEBUG: "true"
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:4.0-alpine
    ports:
      - 6379:6379
